server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://39.101.64.92:3306/cloud_order?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    sentinel:
      web-context-unify: false # 关闭context整合
      transport:
        dashboard: localhost:8089
      datasource:
        flow:
          nacos:
            server-addr: 39.101.64.92:8848 # nacos地址
            dataId: orderservice-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: flow # 还可以是：degrade、authority、param-flow




feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        logger-level: BASIC
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka