server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://172.21.47.218:3306/cloud_order?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver



feign:
  client:
    config:
      default:
        logger-level: BASIC
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka